[project]
name = "security-master"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "faker>=37.12.0",
    "numpy>=2.3.4",
    "pydantic>=2.12.3",
    "redis>=7.0.1",
    "sentence-transformers>=5.1.2",
]
